spring.application.name=w1crud.coffestore


server.port=6969
spring.datasource.url=jdbc:postgresql://localhost:5432/hsf302
spring.datasource.username=postgres
spring.datasource.password=25251325
spring.datasource.driver-class-name=org.postgresql.Driver

#never use ddl-auto in production!
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#Those lines to let liquibase use a different Database compare to main application
#spring.liquibase.url=jdbc:postgresql://localhost:5432/mydb
#spring.liquibase.user=migration_admin
#spring.liquibase.password=secure_password
spring.liquibase.change-log=db/changelog/06-01-changelog.sql
spring.liquibase.enabled=true
spring.liquibase.default-schema=public
spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html