spring.application.name=w1crud.coffestore


server.port=6969

spring.datasource.url=jdbc:postgresql://localhost:5432/hsf302
spring.datasource.username=postgres
spring.datasource.password=25251325
spring.datasource.driver-class-name=org.postgresql.Driver
#never use ddl-auto in production!
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html